-- ============================================================
-- TryoutKu - Soal UTBK Tambahan (Soal 21-40)
-- Melengkapi setiap tryout UTBK menjadi 40 soal
-- ============================================================

-- ============================================================
-- SOAL 21-40: TPS - PENALARAN UMUM
-- ============================================================
INSERT INTO questions (tryout_id, nomor, soal, pilihan, jawaban_benar, pembahasan, poin)
SELECT t.id, q.nomor, q.soal, q.pilihan::jsonb, q.jawaban_benar, q.pembahasan, 1
FROM tryouts t, (VALUES
(21, 'DOKTER : RUMAH SAKIT :: HAKIM : ...', '{"a":"Penjara","b":"Kepolisian","c":"Pengadilan","d":"Kejaksaan","e":"Kantor"}', 'c', 'Dokter bekerja di rumah sakit, hakim bekerja di pengadilan. Analogi: profesi dan tempat kerjanya.'),
(22, 'Deret: 1, 4, 9, 16, 25, 36, ... Angka berikutnya adalah...', '{"a":"42","b":"45","c":"47","d":"49","e":"51"}', 'd', 'Deret bilangan kuadrat: 1², 2², 3², 4², 5², 6², 7² = 49.'),
(23, 'Jika semua A adalah B, dan tidak ada B yang merupakan C, maka...', '{"a":"Semua A adalah C","b":"Tidak ada A yang merupakan C","c":"Beberapa A adalah C","d":"Semua C adalah A","e":"Tidak dapat disimpulkan"}', 'b', 'Semua A adalah B; tidak ada B = C → tidak ada A yang C (transitif).'),
(24, 'LAUT : NELAYAN :: HUTAN : ...', '{"a":"Petani","b":"Pemburu","c":"Peternak","d":"Penebang","e":"Pekebun"}', 'b', 'Nelayan mencari nafkah di laut; pemburu mencari nafkah di hutan.'),
(25, 'Deret: 2, 6, 12, 20, 30, 42, ... Angka berikutnya adalah...', '{"a":"52","b":"54","c":"56","d":"58","e":"60"}', 'c', 'Selisih: 4, 6, 8, 10, 12, 14 → 42+14 = 56.'),
(26, 'Jika P > Q, Q > R, dan R > S, maka pernyataan yang PASTI benar adalah...', '{"a":"S > P","b":"P > S","c":"Q > S hanya kadang-kadang","d":"R = Q","e":"Tidak dapat ditentukan"}', 'b', 'P>Q>R>S, maka P>S (sifat transitif perbandingan).'),
(27, 'PANAS : TERMOMETER :: TEKANAN : ...', '{"a":"Barometer","b":"Anemometer","c":"Higrometer","d":"Seismograf","e":"Altimeter"}', 'a', 'Termometer mengukur suhu/panas; barometer mengukur tekanan udara.'),
(28, 'Deret huruf: Z, X, V, T, R, ... Huruf berikutnya adalah...', '{"a":"P","b":"Q","c":"O","d":"N","e":"M"}', 'a', 'Urutan mundur melompat satu: Z(26), X(24), V(22), T(20), R(18), P(16).'),
(29, 'Ani lebih pintar dari Budi. Cici lebih pintar dari Ani. Dedi sama pintarnya dengan Cici. Siapa yang paling pintar?', '{"a":"Ani","b":"Budi","c":"Cici","d":"Dedi","e":"Cici dan Dedi sama"}', 'e', 'Cici > Ani > Budi. Dedi = Cici. Maka Cici dan Dedi sama-sama paling pintar.'),
(30, 'BUKU : PENGETAHUAN :: MAKANAN : ...', '{"a":"Lapar","b":"Energi","c":"Masak","d":"Restoran","e":"Gizi"}', 'b', 'Buku memberikan pengetahuan; makanan memberikan energi. Analogi: sumber → manfaat yang diberikan.'),
(31, 'Deret: 3, 7, 15, 31, 63, ... Angka berikutnya adalah...', '{"a":"105","b":"117","c":"125","d":"127","e":"135"}', 'd', 'Pola: ×2+1. 3→7(×2+1), 7→15, 15→31, 31→63, 63→127.'),
(32, 'Semua burung bisa terbang. Penguin adalah burung. Namun penguin tidak bisa terbang. Ini adalah contoh...', '{"a":"Silogisme valid","b":"Induksi yang benar","c":"Premis yang salah (semua burung bisa terbang)","d":"Kesimpulan yang valid","e":"Deduksi sempurna"}', 'c', 'Premis "semua burung bisa terbang" salah karena penguin adalah pengecualian. Kesalahan ada pada premis.'),
(33, 'OMBAK : ANGIN :: GEMPA : ...', '{"a":"Tsunami","b":"Pergeseran lempeng tektonik","c":"Gunung berapi","d":"Banjir","e":"Badai"}', 'b', 'Angin menyebabkan ombak; pergeseran lempeng tektonik menyebabkan gempa. Analogi: penyebab → akibat.'),
(34, 'Deret: 1, 2, 4, 7, 11, 16, 22, ... Angka berikutnya adalah...', '{"a":"28","b":"29","c":"30","d":"31","e":"32"}', 'b', 'Selisih: 1,2,3,4,5,6,7 → 22+7 = 29.'),
(35, 'Jika tidak ada siswa yang malas lulus ujian, dan Rani tidak lulus ujian, maka...', '{"a":"Rani pintar","b":"Rani malas","c":"Rani tidak belajar","d":"Rani mungkin malas","e":"Tidak dapat disimpulkan"}', 'b', 'Tidak ada siswa malas yang lulus ujian. Rani tidak lulus → Rani malas.'),
(36, 'SIANG : MATAHARI :: MALAM : ...', '{"a":"Gelap","b":"Bulan","c":"Bintang","d":"Tidur","e":"Lampu"}', 'b', 'Siang identik dengan matahari; malam identik dengan bulan. Analogi: waktu → benda langit yang dominan.'),
(37, 'Deret: 100, 91, 83, 76, 70, 65, ... Angka berikutnya adalah...', '{"a":"60","b":"61","c":"62","d":"63","e":"64"}', 'b', 'Selisih: -9,-8,-7,-6,-5,-4 → 65-4 = 61.'),
(38, 'KOKI : DAPUR :: PILOT : ...', '{"a":"Bandara","b":"Pesawat","c":"Langit","d":"Runway","e":"Menara kontrol"}', 'b', 'Koki bekerja di dalam dapur; pilot bekerja di dalam pesawat (kokpit).'),
(39, 'Lima tim A, B, C, D, E berlomba. A lebih cepat dari C. D lebih lambat dari B. E paling cepat. C lebih cepat dari D. Urutan dari tercepat adalah...', '{"a":"E,A,C,D,B","b":"E,B,A,C,D","c":"E,A,B,C,D","d":"E,A,C,B,D","e":"Tidak dapat ditentukan"}', 'e', 'Dari clue: E>paling cepat; A>C>D; D<B. Posisi B dan A terhadap satu sama lain tidak diketahui. Tidak dapat ditentukan urutan pasti.'),
(40, 'GELOMBANG : FREKUENSI :: PENDULUM : ...', '{"a":"Amplitudo","b":"Massa","c":"Periode","d":"Panjang","e":"Gaya"}', 'c', 'Gelombang dikarakterisasi oleh frekuensi; pendulum dikarakterisasi oleh periode. Keduanya adalah besaran waktu dalam gerak periodik.')
) AS q(nomor, soal, pilihan, jawaban_benar, pembahasan)
WHERE t.title = 'UTBK TPS - Penalaran Umum'
ON CONFLICT (tryout_id, nomor) DO NOTHING;
UPDATE tryouts SET jumlah_soal = 40 WHERE title = 'UTBK TPS - Penalaran Umum';

-- ============================================================
-- SOAL 21-40: TPS - PENGETAHUAN KUANTITATIF
-- ============================================================
INSERT INTO questions (tryout_id, nomor, soal, pilihan, jawaban_benar, pembahasan, poin)
SELECT t.id, q.nomor, q.soal, q.pilihan::jsonb, q.jawaban_benar, q.pembahasan, 1
FROM tryouts t, (VALUES
(21, 'Sebuah dadu dilempar sekali. Peluang muncul bilangan genap adalah...', '{"a":"1/6","b":"1/3","c":"1/2","d":"2/3","e":"5/6"}', 'c', 'Bilangan genap pada dadu: 2,4,6 = 3 dari 6 sisi. P = 3/6 = 1/2.'),
(22, 'Jika 3a - 2b = 10 dan a + b = 5, maka nilai a adalah...', '{"a":"2","b":"3","c":"4","d":"5","e":"6"}', 'c', 'Dari a+b=5 → b=5-a. Substitusi: 3a-2(5-a)=10 → 3a-10+2a=10 → 5a=20 → a=4.'),
(23, 'Volume kerucut dengan jari-jari 6 cm dan tinggi 7 cm (π=22/7) adalah...', '{"a":"264 cm³","b":"276 cm³","c":"288 cm³","d":"300 cm³","e":"312 cm³"}', 'a', 'V = (1/3)πr²t = (1/3)(22/7)(36)(7) = (1/3)(22)(36) = 264 cm³.'),
(24, 'Jumlah deret geometri tak hingga dengan a=8 dan r=1/2 adalah...', '{"a":"12","b":"14","c":"16","d":"18","e":"20"}', 'c', 'S∞ = a/(1-r) = 8/(1-1/2) = 8/(1/2) = 16.'),
(25, 'Dari 6 orang akan dipilih 2 orang sebagai ketua dan sekretaris. Banyaknya cara adalah...', '{"a":"12","b":"15","c":"20","d":"30","e":"36"}', 'd', 'Permutasi: ⁶P₂ = 6×5 = 30 cara (urutan penting: ketua ≠ sekretaris).'),
(26, 'Nilai dari (0,4)² + (0,3)² = ...', '{"a":"0,16","b":"0,25","c":"0,49","d":"0,5","e":"0,65"}', 'b', '(0,4)² = 0,16. (0,3)² = 0,09. Jumlah = 0,25.'),
(27, 'Sebuah proyek bisa diselesaikan 12 hari oleh 8 orang. Jika ingin selesai dalam 6 hari, dibutuhkan berapa orang?', '{"a":"12","b":"14","c":"16","d":"18","e":"20"}', 'c', 'Total kerja = 8×12 = 96 hari-orang. Orang = 96/6 = 16.'),
(28, 'Akar-akar persamaan 3x² - 7x + 2 = 0 adalah...', '{"a":"x=2 dan x=1/3","b":"x=-2 dan x=-1/3","c":"x=2 dan x=-1/3","d":"x=1/2 dan x=2","e":"x=1 dan x=2/3"}', 'a', '3x²-7x+2=0 → (3x-1)(x-2)=0 → x=1/3 atau x=2.'),
(29, 'Persentase kenaikan dari 80 menjadi 100 adalah...', '{"a":"15%","b":"20%","c":"25%","d":"30%","e":"35%"}', 'c', '% naik = (100-80)/80 × 100% = 20/80 × 100% = 25%.'),
(30, 'Jika log 2 = 0,301 dan log 3 = 0,477, maka log 12 = ...', '{"a":"0,778","b":"0,954","c":"1,079","d":"1,176","e":"1,301"}', 'c', 'log 12 = log(4×3) = log 4 + log 3 = 2log2 + log3 = 0,602+0,477 = 1,079.'),
(31, 'Luas permukaan bola dengan jari-jari 7 cm (π=22/7) adalah...', '{"a":"616 cm²","b":"308 cm²","c":"154 cm²","d":"462 cm²","e":"528 cm²"}', 'a', 'L = 4πr² = 4×(22/7)×49 = 4×22×7 = 616 cm².'),
(32, 'Suatu barisan geometri: 2, 6, 18, 54, ... Jumlah 6 suku pertama adalah...', '{"a":"728","b":"730","c":"732","d":"734","e":"736"}', 'a', 'S₆ = a(rⁿ-1)/(r-1) = 2(3⁶-1)/(3-1) = 2(729-1)/2 = 728.'),
(33, 'Nilai dari tan 30° + sin 60° = ...', '{"a":"√3/3 + √3/2","b":"√3","c":"√3/3","d":"2√3/3","e":"5√3/6"}', 'e', 'tan30°=√3/3=1/√3. sin60°=√3/2. Jumlah = √3/3+√3/2 = 2√3/6+3√3/6 = 5√3/6.'),
(34, 'Suatu data memiliki rata-rata 70. Jika semua nilai ditambah 5, rata-rata baru adalah...', '{"a":"70","b":"72","c":"75","d":"77","e":"80"}', 'c', 'Menambahkan konstanta k ke semua data menggeser rata-rata sebesar k. 70+5 = 75.'),
(35, 'Harga 3 pulpen dan 2 buku = Rp 24.000. Harga 2 pulpen dan 3 buku = Rp 26.000. Harga 1 pulpen adalah...', '{"a":"Rp 3.000","b":"Rp 3.200","c":"Rp 4.000","d":"Rp 4.200","e":"Rp 5.000"}', 'c', '3p+2b=24000 ... (1); 2p+3b=26000 ... (2). (1)×3-(2)×2: 9p+6b-4p-6b=72000-52000 → 5p=20000 → p=4000.'),
(36, 'Diketahui vektor a=(3,4). Panjang vektor |a| adalah...', '{"a":"3","b":"4","c":"5","d":"6","e":"7"}', 'c', '|a| = √(3²+4²) = √(9+16) = √25 = 5.'),
(37, 'Nilai dari sin²45° + cos²45° + tan²45° = ...', '{"a":"1","b":"1,5","c":"2","d":"2,5","e":"3"}', 'c', 'sin²45°+cos²45° = 1 (identitas). tan²45° = 1² = 1. Total = 1+1 = 2.'),
(38, 'Sebuah segitiga siku-siku memiliki kaki 5 cm dan 12 cm. Hipotenusanya adalah...', '{"a":"13 cm","b":"14 cm","c":"15 cm","d":"16 cm","e":"17 cm"}', 'a', 'c = √(5²+12²) = √(25+144) = √169 = 13 cm. (Tripel Pythagoras 5-12-13).'),
(39, 'Modus dari data: 5, 7, 7, 8, 9, 9, 9, 10, 10 adalah...', '{"a":"7","b":"8","c":"9","d":"10","e":"9 dan 10"}', 'c', 'Modus = nilai yang paling sering muncul. Angka 9 muncul 3 kali (paling banyak).'),
(40, 'Jika f(x) = 2x+3 dan g(x) = x²-1, maka (g∘f)(2) = ...', '{"a":"46","b":"48","c":"50","d":"52","e":"54"}', 'b', 'f(2) = 2(2)+3 = 7. g(f(2)) = g(7) = 7²-1 = 49-1 = 48.')
) AS q(nomor, soal, pilihan, jawaban_benar, pembahasan)
WHERE t.title = 'UTBK TPS - Pengetahuan Kuantitatif'
ON CONFLICT (tryout_id, nomor) DO NOTHING;
UPDATE tryouts SET jumlah_soal = 40 WHERE title = 'UTBK TPS - Pengetahuan Kuantitatif';

-- ============================================================
-- SOAL 21-40: TKA SAINTEK - MATEMATIKA
-- ============================================================
INSERT INTO questions (tryout_id, nomor, soal, pilihan, jawaban_benar, pembahasan, poin)
SELECT t.id, q.nomor, q.soal, q.pilihan::jsonb, q.jawaban_benar, q.pembahasan, 1
FROM tryouts t, (VALUES
(21, 'Turunan dari f(x) = x²·sin x adalah...', '{"a":"2x·sin x + x²·cos x","b":"2x·cos x","c":"x²·cos x","d":"2x·sin x","e":"2x·sin x - x²·cos x"}', 'a', 'Aturan hasil kali: f''=(u''v+uv'') = 2x·sinx + x²·cosx.'),
(22, 'Nilai dari ∫₀^(π/2) cos x dx = ...', '{"a":"0","b":"1/2","c":"1","d":"π/2","e":"2"}', 'c', '[sin x]₀^(π/2) = sin(π/2) - sin(0) = 1 - 0 = 1.'),
(23, 'Jika matriks A = [[2,1],[3,2]], invers A adalah...', '{"a":"[[2,-1],[-3,2]]","b":"[[-2,1],[3,-2]]","c":"[[2,3],[1,2]]","d":"[[-2,-1],[-3,-2]]","e":"[[1,0],[0,1]]"}', 'a', 'det A = 2(2)-1(3)=1. A⁻¹ = (1/det)[[d,-b],[-c,a]] = [[2,-1],[-3,2]].'),
(24, 'Himpunan penyelesaian |2x - 3| < 5 adalah...', '{"a":"x < -1 atau x > 4","b":"-1 < x < 4","c":"-4 < x < 1","d":"x < -4 atau x > 1","e":"-1 ≤ x ≤ 4"}', 'b', '|2x-3| < 5 → -5 < 2x-3 < 5 → -2 < 2x < 8 → -1 < x < 4.'),
(25, 'Persamaan garis singgung kurva y = x³ di titik (1,1) adalah...', '{"a":"y = x","b":"y = 3x - 2","c":"y = 3x + 2","d":"y = x + 2","e":"y = 2x - 1"}', 'b', 'y'' = 3x². Di x=1: m = 3. Garis singgung: y-1 = 3(x-1) → y = 3x-2.'),
(26, 'Nilai dari ∑(k=1 hingga 5) (2k+1) = ...', '{"a":"30","b":"35","c":"40","d":"45","e":"50"}', 'b', '(3)+(5)+(7)+(9)+(11) = 35.'),
(27, 'Jika cos 2α = 7/25, maka cos²α = ...', '{"a":"7/25","b":"16/25","c":"9/25","d":"4/5","e":"3/5"}', 'b', 'cos 2α = 2cos²α - 1 → 7/25 = 2cos²α - 1 → 2cos²α = 32/25 → cos²α = 16/25.'),
(28, 'Daerah yang dibatasi y = 4 - x² dan sumbu x memiliki luas...', '{"a":"16/3","b":"32/3","c":"8","d":"16","e":"32"}', 'b', 'Kurva memotong sumbu x di x=±2. L = ∫₋₂² (4-x²)dx = [4x-x³/3]₋₂² = (8-8/3)-(-8+8/3) = 32/3.'),
(29, 'Suku banyak P(x) = 2x³ - 3x² + x - 5 dibagi (x-2), sisanya adalah...', '{"a":"-3","b":"-1","c":"1","d":"3","e":"5"}', 'c', 'Teorema Sisa: P(2) = 2(8)-3(4)+2-5 = 16-12+2-5 = 1.'),
(30, 'Nilai dari lim(x→∞) (3x² + 2x) / (x² - 5) = ...', '{"a":"0","b":"1","c":"2","d":"3","e":"∞"}', 'd', 'Bagi pembilang dan penyebut dengan x². Hasil: (3+2/x)/(1-5/x²) → 3/1 = 3.'),
(31, 'Jika titik A(2,3), B(5,7), C(-1,1) adalah titik-titik segitiga, luas segitiga ABC adalah...', '{"a":"5","b":"7","c":"9","d":"11","e":"13"}', 'a', 'L = ½|x_A(y_B-y_C)+x_B(y_C-y_A)+x_C(y_A-y_B)| = ½|2(6)+5(-2)+(-1)(-4)| = ½|12-10+4| = ½(6) = ... Let me recalculate: ½|2(7-1)+5(1-3)+(-1)(3-7)| = ½|12-10+4| = ½×6... Hmm wait: ½|2(6)+5(-2)+(-1)(-4)| = ½|12-10+4|=½×6=3... Let me try again properly: A(2,3),B(5,7),C(-1,1). L=½|(x_A-x_C)(y_B-y_A)-(x_A-x_B)(y_C-y_A)| = ½|(3)(4)-(-3)(-2)| = ½|12-6| = 3. Actually using determinant formula: ½|2(7-1)+5(1-3)+(-1)(3-7)| = ½|12-10+4| = ½×6 = 3... but answer says 5. Let me use Shoelace: ½|2·7+5·1+(-1)·3 - (3·5+7·(-1)+1·2)| = ½|14+5-3-(15-7+2)| = ½|16-10| = ½×6 = 3. Answer should be 3, let me fix.'),
(32, 'Nilai diskriminan dari 5x² - 3x + 1 = 0 adalah...', '{"a":"29","b":"11","c":"-11","d":"-20","e":"-29"}', 'c', 'D = b²-4ac = 9 - 4(5)(1) = 9 - 20 = -11. D < 0 berarti tidak ada akar real.'),
(33, 'Turunan kedua dari f(x) = 4x³ - 3x² + 2x - 7 adalah...', '{"a":"24x - 6","b":"12x² - 6x + 2","c":"12x - 6","d":"24x - 3","e":"12x² - 3x"}', 'a', 'f''(x) = 12x²-6x+2. f''''(x) = 24x-6.'),
(34, 'Jika dua dadu dilempar, peluang jumlah mata = 7 adalah...', '{"a":"1/12","b":"1/9","c":"1/6","d":"5/36","e":"7/36"}', 'c', 'Pasangan yang berjumlah 7: (1,6),(2,5),(3,4),(4,3),(5,2),(6,1) = 6 pasang. P = 6/36 = 1/6.'),
(35, 'Nilai minimum fungsi f(x) = x² - 6x + 11 adalah...', '{"a":"2","b":"3","c":"4","d":"5","e":"6"}', 'a', 'x minimum = -b/2a = 6/2 = 3. f(3) = 9-18+11 = 2.'),
(36, 'Panjang busur lingkaran dengan jari-jari 10 cm dan sudut pusat 60° adalah...', '{"a":"π/3 cm","b":"10π/3 cm","c":"10π cm","d":"20π/3 cm","e":"20π cm"}', 'b', 'Panjang busur = (θ/360°)×2πr = (60/360)×2π×10 = (1/6)×20π = 10π/3 cm.'),
(37, 'Solusi dari persamaan 2^(x+1) = 32 adalah...', '{"a":"x = 3","b":"x = 4","c":"x = 5","d":"x = 6","e":"x = 7"}', 'b', '2^(x+1) = 2⁵ → x+1 = 5 → x = 4.'),
(38, 'Jika fungsi f(x) = ax + b memiliki f(1) = 3 dan f(-1) = -1, maka a + b = ...', '{"a":"1","b":"2","c":"3","d":"4","e":"5"}', 'c', 'f(1)=a+b=3. f(-1)=-a+b=-1. Jumlah: 2b=2 → b=1. a=2. a+b = 3.'),
(39, 'Nilai dari sin(A+B) jika sin A = 3/5 dan cos B = 5/13 (A,B di kuadran I) adalah...', '{"a":"16/65","b":"33/65","c":"56/65","d":"63/65","e":"64/65"}', 'c', 'cos A=4/5, sin B=12/13. sin(A+B)=sinAcosB+cosAsinB=(3/5)(5/13)+(4/5)(12/13)=15/65+48/65=63/65. Wait: 15+48=63. Answer is d.'),
(40, 'Banyak bilangan genap 3-digit yang dapat dibentuk dari angka {1,2,3,4,5} tanpa pengulangan adalah...', '{"a":"20","b":"24","c":"30","d":"40","e":"48"}', 'b', 'Digit terakhir harus genap: pilihan 2 atau 4 (2 cara). Digit pertama: 4 cara (dari 5, kurang 1 yang sudah dipakai). Digit kedua: 3 cara. Total = 2×4×3 = 24.')
) AS q(nomor, soal, pilihan, jawaban_benar, pembahasan)
WHERE t.title = 'UTBK TKA Saintek - Matematika'
ON CONFLICT (tryout_id, nomor) DO NOTHING;
UPDATE tryouts SET jumlah_soal = 40 WHERE title = 'UTBK TKA Saintek - Matematika';

-- Fix soal 31 dan 39 yang salah hitung di atas
UPDATE questions SET
  pilihan = '{"a":"2","b":"3","c":"4","d":"5","e":"6"}'::jsonb,
  jawaban_benar = 'b',
  pembahasan = 'Shoelace formula: L=½|x_A(y_B-y_C)+x_B(y_C-y_A)+x_C(y_A-y_B)| = ½|2(7-1)+5(1-3)+(-1)(3-7)| = ½|12-10+4| = ½×6 = 3. Jawaban paling mendekati adalah 3.'
WHERE nomor = 31 AND tryout_id = (SELECT id FROM tryouts WHERE title = 'UTBK TKA Saintek - Matematika');

UPDATE questions SET
  jawaban_benar = 'd',
  pembahasan = 'cosA=4/5, sinB=12/13. sin(A+B)=sinAcosB+cosAsinB=(3/5)(5/13)+(4/5)(12/13)=15/65+48/65=63/65.'
WHERE nomor = 39 AND tryout_id = (SELECT id FROM tryouts WHERE title = 'UTBK TKA Saintek - Matematika');

-- ============================================================
-- SOAL 21-40: TKA SAINTEK - FISIKA
-- ============================================================
INSERT INTO questions (tryout_id, nomor, soal, pilihan, jawaban_benar, pembahasan, poin)
SELECT t.id, q.nomor, q.soal, q.pilihan::jsonb, q.jawaban_benar, q.pembahasan, 1
FROM tryouts t, (VALUES
(21, 'Sebuah pegas dengan konstanta 200 N/m diregangkan 10 cm. Energi potensial pegas adalah...', '{"a":"0,5 J","b":"1 J","c":"2 J","d":"10 J","e":"20 J"}', 'b', 'Ep = ½kx² = ½(200)(0,1)² = ½(200)(0,01) = 1 J.'),
(22, 'Intensitas bunyi yang dua kali lebih tinggi dari 10⁻¹² W/m² dalam dB adalah...', '{"a":"1 dB","b":"3 dB","c":"6 dB","d":"10 dB","e":"20 dB"}', 'b', 'Jika intensitas digandakan, ΔL = 10 log 2 ≈ 10(0,3) = 3 dB.'),
(23, 'Sebuah konduktor memiliki hambatan R. Jika panjangnya digandakan dan luas penampangnya dihalvingkan, hambatan baru adalah...', '{"a":"R","b":"2R","c":"4R","d":"R/2","e":"R/4"}', 'c', 'R = ρL/A. Jika L→2L dan A→A/2: R_baru = ρ(2L)/(A/2) = 4ρL/A = 4R.'),
(24, 'Gelombang elektromagnetik merambat di ruang hampa dengan kecepatan...', '{"a":"Bergantung frekuensi","b":"Bergantung medium","c":"3×10⁸ m/s (konstan)","d":"3×10⁶ m/s","e":"Bergantung amplitudo"}', 'c', 'Semua gelombang EM merambat di vakum dengan kecepatan cahaya c = 3×10⁸ m/s, tidak bergantung frekuensi.'),
(25, 'Sebuah elektron bergerak dengan energi kinetik 50 eV. Dalam Joule, energi itu adalah... (1 eV = 1,6×10⁻¹⁹ J)', '{"a":"8×10⁻¹⁸ J","b":"5×10⁻¹⁷ J","c":"8×10⁻¹⁷ J","d":"5×10⁻¹⁸ J","e":"1,6×10⁻¹⁸ J"}', 'a', 'E = 50 × 1,6×10⁻¹⁹ = 80×10⁻¹⁹ = 8×10⁻¹⁸ J.'),
(26, 'Hukum Snell untuk pembiasan cahaya menyatakan n₁ sin θ₁ = n₂ sin θ₂. Jika cahaya masuk air (n=1,33) dari udara (n=1) dengan θ₁=30°, maka sin θ₂ = ...', '{"a":"0,376","b":"0,5","c":"0,665","d":"0,75","e":"1,33"}', 'a', 'sin θ₂ = (n₁/n₂)×sin θ₁ = (1/1,33)×0,5 ≈ 0,376.'),
(27, 'Pada proses adiabatik, berlaku...', '{"a":"Q = 0","b":"ΔT = 0","c":"ΔU = 0","d":"W = 0","e":"P = konstan"}', 'a', 'Proses adiabatik: tidak ada kalor yang masuk atau keluar (Q = 0). ΔU = -W.'),
(28, 'Jika suhu gas ideal dinaikkan dari 27°C menjadi 327°C pada tekanan konstan, volume menjadi...', '{"a":"Tetap","b":"1,5 kali","c":"2 kali","d":"3 kali","e":"4 kali"}', 'c', 'T₁ = 300 K, T₂ = 600 K. V₂/V₁ = T₂/T₁ = 600/300 = 2. Volume menjadi 2 kali.'),
(29, 'Difraksi cahaya dapat terjadi ketika...', '{"a":"Cahaya melewati dua medium berbeda","b":"Cahaya melewati celah sempit atau tepi penghalang","c":"Cahaya dipantulkan cermin datar","d":"Cahaya dipolarisasi","e":"Cahaya diserap materi"}', 'b', 'Difraksi: pembelokan gelombang saat melewati celah sempit atau penghalang, paling jelas jika lebar celah ~ λ.'),
(30, 'Pada transistor NPN yang aktif, arah aliran arus...', '{"a":"Emiter→Basis→Kolektor","b":"Kolektor→Basis→Emiter","c":"Basis→Emiter dan Basis→Kolektor","d":"Emiter→Kolektor langsung","e":"Kolektor→Emiter dan Basis→Emiter"}', 'e', 'Pada NPN aktif: arus konvensional mengalir dari Kolektor→Emiter dan dari Basis→Emiter.'),
(31, 'Sebuah kapasitor berkapasitansi C dihubungkan seri dengan kapasitor C lain. Kapasitansi total adalah...', '{"a":"2C","b":"C","c":"C/2","d":"C/4","e":"4C"}', 'c', 'Kapasitor seri: 1/C_total = 1/C + 1/C = 2/C → C_total = C/2.'),
(32, 'Efek Compton membuktikan bahwa foton memiliki...', '{"a":"Muatan listrik","b":"Massa diam","c":"Momentum","d":"Muatan magnet","e":"Spin"}', 'c', 'Efek Compton (1923): foton bertumbukan dengan elektron dan mengubah panjang gelombang — membuktikan foton memiliki momentum p = h/λ.'),
(33, 'Pada rangkaian LC tanpa hambatan, frekuensi resonansi adalah...', '{"a":"f = 1/(2π√LC)","b":"f = 2π√LC","c":"f = 1/√LC","d":"f = √LC","e":"f = LC/(2π)"}', 'a', 'Frekuensi resonansi rangkaian LC: f₀ = 1/(2π√LC). Ini adalah frekuensi osilasi alami.'),
(34, 'Sebuah bola bermassa 0,5 kg dilempar vertikal ke atas dengan kecepatan 20 m/s. Ketinggian maksimum (g=10 m/s²) adalah...', '{"a":"10 m","b":"15 m","c":"20 m","d":"25 m","e":"30 m"}', 'c', 'h = v₀²/(2g) = 400/20 = 20 m.'),
(35, 'Radiasi benda hitam menurut Hukum Stefan-Boltzmann adalah...', '{"a":"P ∝ T²","b":"P ∝ T³","c":"P ∝ T⁴","d":"P ∝ 1/T","e":"P ∝ T"}', 'c', 'Hukum Stefan-Boltzmann: P = σAT⁴. Daya radiasi berbanding lurus dengan T⁴.'),
(36, 'Sebuah cermin cekung memiliki jari-jari kelengkungan 20 cm. Jarak fokusnya adalah...', '{"a":"5 cm","b":"10 cm","c":"15 cm","d":"20 cm","e":"40 cm"}', 'b', 'f = R/2 = 20/2 = 10 cm.'),
(37, 'Momentum sudut benda yang berputar L = Iω. Jika momen inersia berkurang setengah dan kecepatan sudut tidak berubah, momentum sudut...', '{"a":"Bertambah dua kali","b":"Berkurang setengah","c":"Tetap","d":"Bertambah empat kali","e":"Berkurang seperempat"}', 'b', 'L = Iω. Jika I menjadi I/2 dan ω tetap: L_baru = (I/2)ω = L/2. Berkurang setengah.'),
(38, 'Pergeseran Wien menyatakan bahwa suhu benda hitam dan panjang gelombang maksimum emisi memiliki hubungan...', '{"a":"λ_max berbanding lurus T","b":"λ_max × T = konstan","c":"λ_max = T²","d":"λ_max tidak terkait T","e":"λ_max berbanding lurus 1/T²"}', 'b', 'Hukum pergeseran Wien: λ_max × T = b (konstan Wien ≈ 2,9×10⁻³ m·K). Benda lebih panas → λ lebih pendek.'),
(39, 'Gaya Lorentz pada muatan q bergerak dengan kecepatan v dalam medan magnet B adalah...', '{"a":"F = qv/B","b":"F = qvB sin θ","c":"F = qB/v","d":"F = q/vB","e":"F = qv + B"}', 'b', 'Gaya Lorentz: F = qv × B = qvB sin θ (θ = sudut antara v dan B).'),
(40, 'Pada reaksi fisi uranium-235, satu neutron menabrak inti U-235 menghasilkan Ba-141, Kr-92, dan...', '{"a":"1 neutron","b":"2 neutron","c":"3 neutron","d":"4 neutron","e":"0 neutron"}', 'c', 'U-235 + n → Ba-141 + Kr-92 + 3n. Tiga neutron dihasilkan, memungkinkan reaksi berantai.')
) AS q(nomor, soal, pilihan, jawaban_benar, pembahasan)
WHERE t.title = 'UTBK TKA Saintek - Fisika'
ON CONFLICT (tryout_id, nomor) DO NOTHING;
UPDATE tryouts SET jumlah_soal = 40 WHERE title = 'UTBK TKA Saintek - Fisika';

-- ============================================================
-- SOAL 21-40: TKA SAINTEK - KIMIA
-- ============================================================
INSERT INTO questions (tryout_id, nomor, soal, pilihan, jawaban_benar, pembahasan, poin)
SELECT t.id, q.nomor, q.soal, q.pilihan::jsonb, q.jawaban_benar, q.pembahasan, 1
FROM tryouts t, (VALUES
(21, 'Senyawa manakah yang memiliki ikatan hidrogen antarmolekul?', '{"a":"CH₄","b":"CCl₄","c":"HF","d":"CO₂","e":"N₂"}', 'c', 'Ikatan hidrogen terbentuk jika H terikat pada F, O, atau N. HF memiliki ikatan H yang sangat kuat antaramolekul.'),
(22, 'Entalpi reaksi pembakaran metana CH₄ + 2O₂ → CO₂ + 2H₂O adalah -890 kJ/mol. Reaksi ini bersifat...', '{"a":"Endoterm","b":"Eksoterm","c":"Isoterm","d":"Adiabatik","e":"Isokor"}', 'b', 'ΔH = -890 kJ/mol (negatif) → eksoterm (melepas kalor ke lingkungan).'),
(23, 'Dalam reaksi redoks, agen oksidasi adalah zat yang...', '{"a":"Kehilangan elektron","b":"Mendapatkan elektron","c":"Mengoksidasi dirinya","d":"Bilangan oksidasinya naik","e":"Mereduksi dirinya"}', 'b', 'Agen oksidasi (pengoksidasi) menerima elektron dari zat lain → biloksnya turun → dirinya tereduksi.'),
(24, 'pH larutan NaOH 0,001 M adalah...', '{"a":"3","b":"8","c":"11","d":"12","e":"13"}', 'c', 'NaOH terionisasi penuh: [OH⁻]=10⁻³ M. pOH = 3. pH = 14-3 = 11.'),
(25, 'Pada elektrolisis larutan CuSO₄ dengan elektrode tembaga, yang terjadi di katoda adalah...', '{"a":"Oksidasi Cu","b":"Cu²⁺ + 2e⁻ → Cu (reduksi)","c":"2H₂O → O₂ + 4H⁺ + 4e⁻","d":"SO₄²⁻ dioksidasi","e":"H₂ dilepaskan"}', 'b', 'Katoda = reduksi. Ion Cu²⁺ dari larutan direduksi menjadi Cu padat yang mengendap di katoda.'),
(26, 'Laju reaksi A + B → C dinyatakan r = k[A]²[B]. Jika konsentrasi A digandakan, laju reaksi menjadi...', '{"a":"2 kali","b":"3 kali","c":"4 kali","d":"6 kali","e":"8 kali"}', 'c', 'r = k[A]²[B]. Jika [A] → 2[A]: r_baru = k(2[A])²[B] = 4k[A]²[B] = 4r. Laju menjadi 4 kali.'),
(27, 'Titik ekivalen titrasi HCl (asam kuat) dengan NaOH (basa kuat) adalah...', '{"a":"pH < 7","b":"pH = 7","c":"pH > 7","d":"pH = 0","e":"pH = 14"}', 'b', 'Titrasi asam kuat-basa kuat: titik ekivalen pH = 7 (garam yang terbentuk NaCl bersifat netral).'),
(28, 'Pada prinsip kesetimbangan kimia, penambahan katalis akan...', '{"a":"Menggeser kesetimbangan ke kanan","b":"Menggeser ke kiri","c":"Menaikkan nilai K","d":"Tidak mengubah posisi kesetimbangan, hanya mempercepat tercapainya","e":"Menurunkan nilai K"}', 'd', 'Katalis mempercepat laju reaksi maju dan balik secara proporsional → tidak mengubah posisi/nilai K kesetimbangan.'),
(29, 'Sifat koligatif larutan tidak bergantung pada...', '{"a":"Jumlah partikel zat terlarut","b":"Jenis zat terlarut","c":"Konsentrasi molal","d":"Sifat pelarut","e":"Suhu"}', 'b', 'Sifat koligatif HANYA bergantung pada jumlah partikel (molalitas/konsentrasi), bukan jenis/identitas zat terlarut.'),
(30, 'Benzena C₆H₆ termasuk senyawa aromatik karena...', '{"a":"Memiliki 6 atom karbon","b":"Memiliki 6 atom hidrogen","c":"Memiliki sistem ikatan π terdelokalisasi (aromatisitas Hückel)","d":"Berbentuk cincin","e":"Tidak larut dalam air"}', 'c', 'Aromatisitas: benzena memiliki 6 elektron π terdelokalisasi dalam cincin (4n+2 elektron π, n=1) → stabil.'),
(31, 'Proses pembuatan asam sulfat secara industri menggunakan metode...', '{"a":"Haber-Bosch","b":"Contact (Kontak)","c":"Frasch","d":"Solvay","e":"Leblanc"}', 'b', 'Proses Kontak (Contact Process): SO₂ + ½O₂ → SO₃ (katalis V₂O₅) → SO₃ + H₂O → H₂SO₄.'),
(32, 'Senyawa dengan rumus CH₃-CH₂-OH adalah...', '{"a":"Metanol","b":"Etanol","c":"Propanol","d":"Butanol","e":"Gliserol"}', 'b', 'CH₃-CH₂-OH adalah etanol (C₂H₅OH), alkohol dua karbon yang umum digunakan sebagai pelarut dan bahan bakar.'),
(33, 'Reaksi saponifikasi adalah reaksi...', '{"a":"Pembakaran lemak","b":"Pemecahan gula","c":"Hidrolisis ester dalam basa menghasilkan sabun","d":"Polimerisasi asam amino","e":"Oksidasi alkohol"}', 'c', 'Saponifikasi: hidrolisis ester (lemak/minyak) dengan basa kuat (NaOH/KOH) menghasilkan sabun (garam asam lemak) dan gliserol.'),
(34, 'Dalam sel volta Zn-Cu (galvani), elektrode seng (Zn) berfungsi sebagai...', '{"a":"Katoda, tempat reduksi","b":"Anoda, tempat oksidasi","c":"Elektrode inert","d":"Jembatan garam","e":"Elektrolit"}', 'b', 'Zn memiliki potensial elektrode lebih negatif → Zn mengalami oksidasi → anoda. Cu adalah katoda.'),
(35, 'Polipeptida terbentuk dari monomer...', '{"a":"Glukosa","b":"Asam nukleat","c":"Asam amino","d":"Gliserol dan asam lemak","e":"Nukleotida"}', 'c', 'Polipeptida adalah polimer dari asam amino yang dihubungkan oleh ikatan peptida (-CO-NH-).'),
(36, 'Larutan buffer asam terdiri dari...', '{"a":"Asam kuat dan garamnya","b":"Asam lemah dan basa konjugatnya (garamnya)","c":"Dua asam kuat","d":"Basa kuat dan garamnya","e":"Dua asam lemah"}', 'b', 'Buffer asam: asam lemah (HA) + basa konjugatnya (A⁻ dari garam). Contoh: CH₃COOH + CH₃COONa.'),
(37, 'Konfigurasi elektron ion Fe³⁺ (Z=26) adalah...', '{"a":"[Ar] 3d⁶ 4s²","b":"[Ar] 3d⁵","c":"[Ar] 3d⁴ 4s¹","d":"[Ar] 3d³ 4s²","e":"[Ar] 3d⁶"}', 'b', 'Fe: [Ar]3d⁶4s². Fe³⁺ melepas 3e⁻ (4s² dulu, lalu 1 dari 3d): [Ar]3d⁵.'),
(38, 'Reaksi antara alkena dengan HBr mengikuti...', '{"a":"Aturan Markovnikov","b":"Aturan Saytzeff","c":"Aturan Le Chatelier","d":"Hukum Hess","e":"Aturan Aufbau"}', 'a', 'Aturan Markovnikov: dalam adisi HX ke alkena, H berikatan dengan C yang lebih banyak H (C lebih kaya H).'),
(39, 'Fenol (C₆H₅OH) berbeda dari alkohol biasa karena...', '{"a":"Lebih larut dalam air","b":"Bersifat lebih asam (pKa ~10) karena cincin benzena menstabilkan anion","c":"Tidak bereaksi dengan basa","d":"Memiliki titik didih lebih rendah","e":"Tidak mengandung gugus OH"}', 'b', 'Fenol lebih asam dari alkohol biasa karena anion fenoksida distabilkan oleh resonansi dengan cincin benzena.'),
(40, 'Reaksi polimerisasi adisi berbeda dari kondensasi karena...', '{"a":"Adisi menghasilkan produk sampingan air","b":"Kondensasi tidak ada produk sampingan","c":"Adisi tidak menghasilkan produk sampingan; semua monomer bergabung langsung","d":"Adisi hanya untuk protein","e":"Kondensasi lebih cepat"}', 'c', 'Polimerisasi adisi: monomer (biasanya berikatan rangkap) bergabung tanpa produk sampingan. Kondensasi: ada produk sampingan (H₂O, HCl, dll).')
) AS q(nomor, soal, pilihan, jawaban_benar, pembahasan)
WHERE t.title = 'UTBK TKA Saintek - Kimia'
ON CONFLICT (tryout_id, nomor) DO NOTHING;
UPDATE tryouts SET jumlah_soal = 40 WHERE title = 'UTBK TKA Saintek - Kimia';

-- ============================================================
-- SOAL 21-40: TKA SAINTEK - BIOLOGI
-- ============================================================
INSERT INTO questions (tryout_id, nomor, soal, pilihan, jawaban_benar, pembahasan, poin)
SELECT t.id, q.nomor, q.soal, q.pilihan::jsonb, q.jawaban_benar, q.pembahasan, 1
FROM tryouts t, (VALUES
(21, 'Pada persilangan monohibrid Aa × Aa, rasio fenotip keturunan F2 adalah...', '{"a":"1:1","b":"1:2:1","c":"3:1","d":"2:1","e":"1:3"}', 'c', 'Aa×Aa menghasilkan AA:Aa:aa = 1:2:1. Fenotip dominan (AA+Aa) : resesif (aa) = 3:1.'),
(22, 'Penyakit buta warna (color blindness) diwariskan secara...', '{"a":"Autosomal dominan","b":"Autosomal resesif","c":"X-linked resesif","d":"X-linked dominan","e":"Y-linked"}', 'c', 'Buta warna: gen resesif terpaut kromosom X. Laki-laki XᵇY lebih sering terkena dari perempuan XᵇXᵇ.'),
(23, 'Proses glikolisis menghasilkan (per 1 molekul glukosa)...', '{"a":"2 piruvat, 2 ATP neto, 2 NADH","b":"6 CO₂, 6 H₂O, 36 ATP","c":"2 piruvat, 36 ATP","d":"Oksaloasetat, 2 ATP","e":"2 asetil-KoA, 2 ATP"}', 'a', 'Glikolisis (sitoplasma): 1 glukosa → 2 piruvat + 2 ATP (neto) + 2 NADH.'),
(24, 'Hormon yang mengatur kadar gula darah adalah...', '{"a":"Tiroksin dan adrenalin","b":"Insulin dan glukagon","c":"FSH dan LH","d":"ADH dan aldosteron","e":"Kortisol dan estrogen"}', 'b', 'Insulin (dari sel β pankreas) menurunkan gula darah; glukagon (dari sel α pankreas) meningkatkannya.'),
(25, 'Klorofil a menyerap cahaya paling kuat pada panjang gelombang...', '{"a":"Hijau (520-560 nm)","b":"Kuning (570-590 nm)","c":"Merah (650-700 nm) dan biru-violet (430-450 nm)","d":"Inframerah (>700 nm)","e":"UV (<400 nm)"}', 'c', 'Klorofil a: puncak absorpsi di ~430 nm (biru) dan ~680 nm (merah). Hijau dipantulkan → daun tampak hijau.'),
(26, 'Sistem saraf pusat terdiri dari...', '{"a":"Otak dan sumsum tulang belakang","b":"Saraf kranial dan saraf spinal","c":"Sistem simpatis dan parasimpatis","d":"Neuron sensoris dan motoris","e":"Saraf perifer dan pleksus"}', 'a', 'SSP = otak (encephalon) + sumsum tulang belakang (medulla spinalis). Saraf tepi adalah sistem saraf perifer.'),
(27, 'Persilangan dihibrid AaBb × AaBb menghasilkan rasio fenotip...', '{"a":"1:2:1","b":"3:1","c":"9:3:3:1","d":"1:1:1:1","e":"9:3:4"}', 'c', 'Hukum Mendel II (pemisahan bebas): dihibrid F2 menghasilkan 9:3:3:1 untuk dua gen bebas.'),
(28, 'Epidermis pada hewan berfungsi sebagai...', '{"a":"Tempat pertukaran gas","b":"Pelindung tubuh dari lingkungan luar","c":"Penghasil enzim pencernaan","d":"Pengatur suhu tubuh internal","e":"Pengangkut nutrisi"}', 'b', 'Epidermis = lapisan terluar kulit, berfungsi melindungi dari dehidrasi, patogen, dan kerusakan mekanis.'),
(29, 'Antibiotik bekerja dengan cara...', '{"a":"Membunuh semua mikroorganisme","b":"Menghambat proses metabolisme spesifik bakteri (dinding sel, sintesis protein, dll)","c":"Meningkatkan sistem imun tubuh","d":"Menghancurkan virus","e":"Menghambat reproduksi sel tubuh"}', 'b', 'Antibiotik bersifat selektif: menarget proses spesifik bakteri (mis: penisilin menghambat sintesis dinding sel bakteri).'),
(30, 'Jaringan meristem apikal pada tumbuhan menghasilkan pertumbuhan...', '{"a":"Sekunder (diameter batang)","b":"Primer (memanjang) pada ujung akar dan batang","c":"Lateral (cabang)","d":"Reproduktif (bunga)","e":"Adventif (akar liar)"}', 'b', 'Meristem apikal (ujung) → pertumbuhan primer (memanjang). Meristem lateral (kambium) → pertumbuhan sekunder.'),
(31, 'Prinsip sentral biologi molekuler (central dogma) adalah...', '{"a":"DNA → RNA → Protein","b":"Protein → RNA → DNA","c":"RNA → DNA → Protein","d":"DNA → Protein langsung","e":"Protein → DNA → RNA"}', 'a', 'Central dogma: informasi genetik mengalir dari DNA (replikasi) → transkripsi RNA → translasi Protein.'),
(32, 'Asosiasi simbiosis mutualisme contohnya adalah...', '{"a":"Rafflesia pada inangnya","b":"Kutu pada hewan","c":"Lebah dan bunga","d":"Cacing pita dalam usus","e":"Tali putri pada tanaman inang"}', 'c', 'Mutualisme: kedua pihak untung. Lebah mendapat nektar; bunga dibantu penyerbukan.'),
(33, 'Seleksi alam bekerja pada level...', '{"a":"Gen saja","b":"Individu (fenotip yang diekspresikan)","c":"Populasi saja","d":"Spesies","e":"Ekosistem"}', 'b', 'Seleksi alam bekerja pada fenotip individu: individu dengan fenotip lebih adaptif lebih banyak bereproduksi.'),
(34, 'Hormon FSH (Follicle Stimulating Hormone) pada perempuan berfungsi...', '{"a":"Mempertahankan kehamilan","b":"Merangsang perkembangan folikel ovarium","c":"Merangsang kontraksi rahim","d":"Mengontrol produksi susu","e":"Meningkatkan metabolisme"}', 'b', 'FSH merangsang perkembangan folikel di ovarium dan produksi estrogen. Dihasilkan oleh kelenjar hipofisis anterior.'),
(35, 'Hewan poikilotermik (berdarah dingin) artinya...', '{"a":"Selalu bersuhu rendah","b":"Suhu tubuh mengikuti suhu lingkungan","c":"Tidak memiliki darah","d":"Hidup di lingkungan dingin saja","e":"Memiliki mekanisme termoregulasi sempurna"}', 'b', 'Poikilotermik (ektotermik): suhu tubuh bervariasi sesuai suhu lingkungan. Contoh: ikan, katak, reptil.'),
(36, 'Proses yang menggunakan energi ATP secara langsung dalam sel adalah...', '{"a":"Difusi sederhana","b":"Osmosis","c":"Transpor aktif","d":"Difusi terfasilitasi","e":"Filtrasi"}', 'c', 'Transpor aktif memindahkan zat melawan gradien konsentrasi → memerlukan energi ATP (mis: pompa Na⁺-K⁺).'),
(37, 'Struktur DNA double helix ditemukan oleh...', '{"a":"Mendel dan Morgan","b":"Watson dan Crick (1953)","c":"Darwin dan Wallace","d":"Pasteur dan Koch","e":"Avery, MacLeod, dan McCarty"}', 'b', 'James Watson dan Francis Crick (1953) mendeskripsikan model double helix DNA berdasarkan data difraksi X-ray Rosalind Franklin.'),
(38, 'Pertumbuhan logistik populasi terjadi ketika...', '{"a":"Sumber daya tidak terbatas","b":"Populasi terus tumbuh eksponensial","c":"Pertumbuhan melambat mendekati daya dukung (carrying capacity)","d":"Predator tidak ada","e":"Kompetisi tidak terjadi"}', 'c', 'Pertumbuhan logistik (S-curve): populasi tumbuh eksponensial di awal, lalu melambat mendekati K (daya dukung lingkungan).'),
(39, 'Kelainan Down Syndrome (trisomi 21) paling sering disebabkan oleh kesalahan pada...', '{"a":"Meiosis I (nondisjunction kromosom 21)","b":"Mitosis","c":"Transkripsi","d":"Translasi","e":"Replikasi DNA"}', 'a', 'Nondisjunction pada meiosis I: pasangan kromosom 21 tidak memisah → gamet dengan 2 kromosom 21 → zigot trisomi 21.'),
(40, 'Pembentukan urin di ginjal melalui tahapan berurutan...', '{"a":"Sekresi → Filtrasi → Reabsorpsi","b":"Filtrasi → Reabsorpsi → Sekresi","c":"Reabsorpsi → Sekresi → Filtrasi","d":"Filtrasi → Sekresi → Reabsorpsi","e":"Sekresi → Reabsorpsi → Filtrasi"}', 'b', 'Pembentukan urin: Filtrasi (glomerulus) → Reabsorpsi (tubulus) → Sekresi (tubulus) → urin akhir ke pelvis ginjal.')
) AS q(nomor, soal, pilihan, jawaban_benar, pembahasan)
WHERE t.title = 'UTBK TKA Saintek - Biologi'
ON CONFLICT (tryout_id, nomor) DO NOTHING;
UPDATE tryouts SET jumlah_soal = 40 WHERE title = 'UTBK TKA Saintek - Biologi';

-- ============================================================
-- SOAL 21-40: TKA SOSHUM - SEJARAH
-- ============================================================
INSERT INTO questions (tryout_id, nomor, soal, pilihan, jawaban_benar, pembahasan, poin)
SELECT t.id, q.nomor, q.soal, q.pilihan::jsonb, q.jawaban_benar, q.pembahasan, 1
FROM tryouts t, (VALUES
(21, 'Candi Borobudur dibangun pada masa Dinasti...', '{"a":"Sanjaya","b":"Syailendra","c":"Isyana","d":"Rajasa","e":"Mataram Islam"}', 'b', 'Borobudur dibangun dinasti Syailendra abad ke-8-9 M sebagai candi Buddha terbesar. Prambanan dibangun dinasti Sanjaya.'),
(22, 'Perlawanan Diponegoro (1825-1830) dikenal juga sebagai...', '{"a":"Perang Banjar","b":"Perang Padri","c":"Perang Jawa","d":"Perang Aceh","e":"Perang Makassar"}', 'c', 'Perang Diponegoro (1825-1830) disebut juga Perang Jawa — perang terbesar melawan Belanda, menelan 200.000 korban jiwa.'),
(23, 'Sistem pemerintahan parlementer Indonesia pertama kali diterapkan pada...', '{"a":"1945-1949","b":"1950-1959","c":"1959-1965","d":"1966-1998","e":"1998-sekarang"}', 'b', 'Periode 1950-1959 (Demokrasi Liberal): Indonesia menerapkan sistem parlementer — kabinet bertanggung jawab kepada parlemen.'),
(24, 'Gerakan 30 September 1965 (G30S) menewaskan 7 perwira, kecuali...', '{"a":"Jenderal Ahmad Yani","b":"Jenderal S. Parman","c":"Jenderal A.H. Nasution","d":"Letnan Jenderal Suprapto","e":"Mayor Jenderal D.I. Pandjaitan"}', 'c', 'A.H. Nasution berhasil meloloskan diri dari penculikan G30S meski mengalami luka. Putrinya Ade Irma Suryani tewas.'),
(25, 'Pemilu pertama Indonesia tahun 1955 dimenangkan oleh...', '{"a":"PKI","b":"Masyumi","c":"PNI (urutan pertama suara terbanyak)","d":"NU","e":"PSI"}', 'c', 'Pemilu 1955: 4 besar: PNI (22,3%), Masyumi (20,9%), NU (18,4%), PKI (16,4%). PNI peraih suara terbanyak.'),
(26, 'Perjanjian Renville (1948) menguntungkan Belanda karena...', '{"a":"Indonesia mendapat wilayah lebih luas","b":"Indonesia harus menarik pasukan dari wilayah yang dikuasai Belanda","c":"Belanda mengakui kemerdekaan Indonesia","d":"Dibentuk RIS","e":"Belanda meninggalkan Indonesia"}', 'b', 'Renville: pasukan RI harus mundur dari kantong-kantong di belakang garis Van Mook → merugikan Indonesia.'),
(27, 'Orde Baru di bawah Soeharto mengakhiri kekuasaan dengan cara...', '{"a":"Kudeta militer","b":"Pemilu langsung","c":"Tekanan krisis ekonomi dan demonstrasi mahasiswa 1998","d":"Keputusan MPR","e":"Invasi asing"}', 'c', 'Krisis moneter 1997-1998 + demonstrasi mahasiswa besar-besaran (12-21 Mei 1998) → Soeharto mundur 21 Mei 1998.'),
(28, 'Konferensi Asia-Afrika 1955 menghasilkan Dasasila Bandung yang intinya...', '{"a":"Pembentukan pakta militer Asia","b":"Prinsip-prinsip hidup berdampingan secara damai dan anti-kolonialisme","c":"Pembentukan ASEAN","d":"Perjanjian perdagangan bebas","e":"Persaingan dengan blok Barat dan Timur"}', 'b', 'Dasasila Bandung: 10 prinsip termasuk menghormati kedaulatan, anti-kolonialisme, non-intervensi, dan perdamaian.'),
(29, 'Tokoh pendiri PKI (Partai Komunis Indonesia) adalah...', '{"a":"D.N. Aidit","b":"Muso","c":"Semaun dan Darsono","d":"Tan Malaka","e":"Alimin"}', 'c', 'PKI didirikan oleh Semaun dan Darsono (1920), merupakan partai komunis pertama di Asia.'),
(30, 'Kerajaan Majapahit mencapai puncak kejayaan pada masa Raja...', '{"a":"Raden Wijaya","b":"Jayanagara","c":"Tribhuwana Wijayatunggadewi","d":"Hayam Wuruk","e":"Wikramawardhana"}', 'd', 'Hayam Wuruk (1350-1389) bersama Gajah Mada membawa Majapahit ke puncak kejayaan — menguasai seluruh Nusantara.'),
(31, 'Pemberontakan DI/TII di Jawa Barat dipimpin oleh...', '{"a":"Kahar Muzakkar","b":"Daud Beureueh","c":"Kartosuwiryo","d":"Ibnu Hajar","e":"Andi Azis"}', 'c', 'DI/TII Jawa Barat dipimpin S.M. Kartosuwiryo yang memproklamasikan Negara Islam Indonesia (NII) 7 Agustus 1949.'),
(32, 'Masa Reformasi dimulai dengan jatuhnya Soeharto pada 1998 dan dilanjutkan oleh...', '{"a":"Megawati Soekarnoputri","b":"BJ Habibie","c":"Abdurrahman Wahid","d":"Susilo Bambang Yudhoyono","e":"Try Sutrisno"}', 'b', 'BJ Habibie menggantikan Soeharto sebagai Presiden RI ke-3 (21 Mei 1998 - 20 Oktober 1999), memulai era reformasi.'),
(33, 'Perang Dunia II di Asia Pasifik dipicu oleh serangan Jepang ke...', '{"a":"Manila","b":"Shanghai","c":"Pearl Harbor, Hawaii (7 Desember 1941)","d":"Singapura","e":"Hong Kong"}', 'c', 'Jepang menyerang Pearl Harbor tanpa peringatan 7 Desember 1941 → AS masuk Perang Dunia II.'),
(34, 'Program Transmigrasi pada masa Orde Baru bertujuan untuk...', '{"a":"Meratakan penyebaran penduduk dari Jawa ke luar Jawa","b":"Mengembangkan pariwisata","c":"Membangun ibu kota baru","d":"Mengurangi angkatan bersenjata","e":"Meningkatkan ekspor"}', 'a', 'Transmigrasi: memindahkan penduduk dari Jawa (padat) ke Sumatra, Kalimantan, Sulawesi (jarang) untuk pemerataan.'),
(35, 'Piagam Jakarta (22 Juni 1945) berbeda dari Pembukaan UUD 1945 karena...', '{"a":"Tidak ada perbedaan","b":"Piagam Jakarta mencantumkan kewajiban menjalankan syariat Islam bagi pemeluknya","c":"Piagam Jakarta tidak menyebut Pancasila","d":"UUD 1945 lebih awal dibuat","e":"Piagam Jakarta disetujui lebih banyak pihak"}', 'b', 'Piagam Jakarta: sila 1 berbunyi "Ketuhanan dengan kewajiban menjalankan syariat Islam bagi pemeluk-pemeluknya." Dihapus saat disahkan 18 Agustus 1945.'),
(36, 'Pada masa Demokrasi Terpimpin (1959-1965), lembaga yang paling berkuasa adalah...', '{"a":"DPR yang dipilih rakyat","b":"MPR","c":"Presiden Soekarno dengan kekuasaan terpusat","d":"TNI/Angkatan Bersenjata","e":"PKI"}', 'c', 'Demokrasi Terpimpin: Soekarno sebagai pemimpin besar revolusi memiliki kekuasaan sangat besar — DPR dibubarkan.'),
(37, 'Perang Dingin antara AS dan Soviet berakhir dengan...', '{"a":"Perjanjian damai formal","b":"Bubarnya Uni Soviet 1991 dan runtuhnya Tembok Berlin 1989","c":"Perang nuklir terbatas","d":"Kemenangan AS dalam Perang Vietnam","e":"Pembentukan PBB"}', 'b', 'Perang Dingin berakhir bertahap: Tembok Berlin runtuh 1989, Uni Soviet resmi bubar 25 Desember 1991.'),
(38, 'Sumber sejarah yang paling dapat dipercaya (primer) adalah...', '{"a":"Buku teks sejarah","b":"Dokumen, artefak, dan prasasti dari zaman yang diteliti","c":"Cerita rakyat","d":"Film dokumenter","e":"Ensiklopedia"}', 'b', 'Sumber primer = bukti langsung dari masa yang diteliti (prasasti, dokumen resmi, artefak, foto). Sumber sekunder = interpretasi setelahnya.'),
(39, 'Misi ekspedisi Portugis yang menemukan jalur laut ke Asia melewati Afrika Selatan dipimpin oleh...', '{"a":"Christopher Columbus","b":"Ferdinand Magellan","c":"Vasco da Gama (1498)","d":"Bartholomeu Dias","e":"Alfonso de Albuquerque"}', 'c', 'Vasco da Gama (1498) berlayar dari Portugal ke India melewati Tanjung Harapan, membuka jalur dagang langsung Eropa-Asia.'),
(40, 'Konsep "Bhinneka Tunggal Ika" dalam konteks sejarah Indonesia pertama muncul dalam kitab...', '{"a":"Negarakertagama","b":"Sutasoma (karya Mpu Tantular, abad ke-14)","c":"Arjunawiwaha","d":"Serat Centhini","e":"Babad Tanah Jawi"}', 'b', 'Frasa "Bhinneka Tunggal Ika, tan hana dharma mangrwa" ada dalam Kakawin Sutasoma karya Mpu Tantular (Majapahit, abad 14).')
) AS q(nomor, soal, pilihan, jawaban_benar, pembahasan)
WHERE t.title = 'UTBK TKA Soshum - Sejarah'
ON CONFLICT (tryout_id, nomor) DO NOTHING;
UPDATE tryouts SET jumlah_soal = 40 WHERE title = 'UTBK TKA Soshum - Sejarah';

-- ============================================================
-- SOAL 21-40: TKA SOSHUM - GEOGRAFI
-- ============================================================
INSERT INTO questions (tryout_id, nomor, soal, pilihan, jawaban_benar, pembahasan, poin)
SELECT t.id, q.nomor, q.soal, q.pilihan::jsonb, q.jawaban_benar, q.pembahasan, 1
FROM tryouts t, (VALUES
(21, 'Angin muson barat yang membawa musim hujan ke Indonesia berasal dari...', '{"a":"Samudra Pasifik menuju Australia","b":"Daratan Asia menuju Australia melalui Indonesia","c":"Samudra Hindia menuju Afrika","d":"Australia menuju Asia","e":"Khatulistiwa menuju kutub"}', 'b', 'Muson barat (Des-Mar): tekanan tinggi di Asia → angin bergerak ke Australia (selatan) → melewati lautan Indonesia → membawa uap air → musim hujan.'),
(22, 'Jenis tanah yang terbentuk dari abu vulkanik dan sangat subur di Jawa adalah...', '{"a":"Tanah latosol","b":"Tanah regosol","c":"Tanah alluvial","d":"Tanah andosol","e":"Tanah gambut"}', 'd', 'Tanah andosol terbentuk dari abu vulkanik — sangat subur karena kaya mineral. Banyak di lereng gunung berapi Jawa.'),
(23, 'Konsep region (wilayah) dalam geografi mencakup...', '{"a":"Wilayah administratif saja","b":"Area yang memiliki karakteristik tertentu yang membedakannya dari area lain","c":"Negara-bangsa secara politik","d":"Wilayah yang dipisahkan laut","e":"Daerah iklim tropis saja"}', 'b', 'Region geografi: area yang memiliki homogenitas karakteristik tertentu (fisik, manusia, atau fungsional).'),
(24, 'Gempa bumi tektonik di Indonesia paling sering terjadi karena...', '{"a":"Aktivitas vulkanik","b":"Pergerakan dan tumbukan lempeng tektonik","c":"Abrasi pantai","d":"Penambangan berlebihan","e":"Perubahan iklim"}', 'b', 'Indonesia berada di pertemuan 3 lempeng besar (Eurasia, Indo-Australia, Pasifik) → sering gempa tektonik.'),
(25, 'Piramida penduduk tipe muda (expansive) menunjukkan...', '{"a":"Angka kelahiran rendah, kematian rendah","b":"Angka kelahiran tinggi, kematian tinggi, dan banyak penduduk muda","c":"Populasi yang menua","d":"Negara maju dengan fertilitas rendah","e":"Jumlah laki-laki dan perempuan seimbang di semua usia"}', 'b', 'Piramida ekspansif (tipe muda): basis lebar (banyak anak), puncak sempit → angka kelahiran tinggi, banyak penduduk usia muda. Tipikal negara berkembang.'),
(26, 'Sungai yang airnya berasal dari curah hujan di daerah tropis dan tidak pernah kering disebut...', '{"a":"Sungai episodik","b":"Sungai periodik","c":"Sungai perenial","d":"Sungai konsekuen","e":"Sungai gletser"}', 'c', 'Sungai perenial (abadi): mengalir sepanjang tahun. Di tropis seperti Indonesia, umumnya bersifat perenial.'),
(27, 'Hutan mangrove di Indonesia berfungsi sebagai...', '{"a":"Sumber kayu industri utama","b":"Pelindung pantai dari abrasi dan habitat berbagai biota","c":"Area pertanian","d":"Sumber air bersih","e":"Kawasan industri"}', 'b', 'Mangrove: melindungi pantai dari erosi/abrasi, menjadi nursery ground ikan dan udang, menyerap karbon.'),
(28, 'Bonus demografi Indonesia diperkirakan terjadi pada...', '{"a":"2000-2010","b":"2010-2020","c":"2020-2040","d":"2050-2060","e":"2070-2080"}', 'c', 'Indonesia diperkirakan menikmati bonus demografi (penduduk usia produktif > non-produktif) sekitar 2020-2040.'),
(29, 'Fenomena La Niña berdampak di Indonesia berupa...', '{"a":"Kekeringan panjang","b":"Curah hujan lebih tinggi dari normal","c":"Suhu udara turun drastis","d":"Badai tropis lebih banyak","e":"Tidak ada dampak signifikan"}', 'b', 'La Niña: suhu permukaan laut Pasifik lebih dingin dari normal → angin lebih kencang menuju Indonesia → curah hujan meningkat.'),
(30, 'Pertanian sawah terasering (sengkedan) di daerah pegunungan bertujuan untuk...', '{"a":"Menambah luas lahan","b":"Mencegah erosi dan memperlambat aliran air","c":"Meningkatkan suhu tanah","d":"Mengurangi kelembaban","e":"Memudahkan mekanisasi pertanian"}', 'b', 'Terasering: lahan miring dibuat bertangga → mengurangi kecepatan aliran air → mencegah erosi → mempertahankan kesuburan.'),
(31, 'Garis Wallace di Indonesia memisahkan fauna...', '{"a":"Asia Tenggara dan Australia","b":"Tipe Oriental (Asia) di barat dengan tipe Australis di timur","c":"Fauna darat dan laut","d":"Fauna Sumatra dan Kalimantan","e":"Fauna SMA dan SD"}', 'b', 'Garis Wallace (antara Kalimantan-Sulawesi dan Bali-Lombok): memisahkan fauna tipe Oriental (Sumatra, Jawa, Kalimantan, Bali) dari fauna Australis (Sulawesi ke timur).'),
(32, 'Interpretasi foto udara dan citra satelit menggunakan prinsip...', '{"a":"Segitiga trigonometri","b":"Unsur interpretasi: rona, bentuk, ukuran, tekstur, pola, bayangan, lokasi, asosiasi","c":"Hanya warna dan ukuran","d":"GPS dan koordinat","e":"Triangulasi GPS"}', 'b', 'Interpretasi citra: rona (kecerahan), bentuk, ukuran, tekstur, pola, bayangan, situs (lokasi), asosiasi.'),
(33, 'Negara-negara ASEAN yang berbatasan langsung dengan laut memiliki keuntungan berupa...', '{"a":"Iklim lebih dingin","b":"Akses perdagangan maritim yang luas","c":"Lebih sedikit bencana alam","d":"Kepadatan penduduk lebih rendah","e":"Pertanian lebih produktif"}', 'b', 'Akses laut → jalur perdagangan internasional lebih mudah → pertumbuhan ekonomi melalui ekspor-impor dan pariwisata bahari.'),
(34, 'Perubahan iklim global menyebabkan kenaikan permukaan laut karena...', '{"a":"Hujan lebih deras","b":"Pencairan es di kutub dan pemuaian air laut akibat suhu naik","c":"Gempa di dasar laut","d":"Polusi industri","e":"Deforestasi"}', 'b', 'Global warming → pencairan gletser/es kutub + pemuaian termal air laut → sea level rise. Ancaman bagi pulau-pulau kecil.'),
(35, 'Konsep agraria Von Thunen menjelaskan bahwa pertanian yang paling intensif berada...', '{"a":"Paling jauh dari kota","b":"Di tengah kota","c":"Paling dekat dengan pasar (pusat kota)","d":"Di daerah pegunungan","e":"Di tepi sungai"}', 'c', 'Von Thunen: lahan paling dekat pasar = biaya transportasi paling kecil → digunakan untuk pertanian paling intensif (sayuran, susu).'),
(36, 'Sumber daya alam yang dapat diperbarui (renewable) adalah...', '{"a":"Minyak bumi","b":"Gas alam","c":"Batu bara","d":"Hutan (dengan pengelolaan)","e":"Timah"}', 'd', 'Hutan adalah SDA terbarukan jika dikelola berkelanjutan (reboisasi). Minyak, gas, batu bara, timah adalah SDA tak terbarukan.'),
(37, 'Pertumbuhan kota yang tidak terkendali (urban sprawl) menyebabkan...', '{"a":"Penurunan harga tanah perkotaan","b":"Berkurangnya kemacetan","c":"Konversi lahan pertanian dan degradasi lingkungan","d":"Meningkatnya kualitas hidup penduduk","e":"Penurunan polusi udara"}', 'c', 'Urban sprawl: kota meluas ke pinggiran → lahan pertanian, hijau, dan resapan air berkurang → banjir, polusi, dan kehilangan lahan produktif.'),
(38, 'Tingkat fertilitas total (TFR) menunjukkan...', '{"a":"Jumlah penduduk total","b":"Rata-rata anak yang dilahirkan seorang wanita selama usia reproduksinya","c":"Angka kematian bayi","d":"Laju pertumbuhan penduduk","e":"Rasio jenis kelamin"}', 'b', 'TFR (Total Fertility Rate): rata-rata jumlah anak yang dilahirkan seorang wanita selama masa reproduksinya (15-49 tahun).'),
(39, 'Penggunaan model SWOT dalam geografi regional bertujuan untuk...', '{"a":"Menghitung luas wilayah","b":"Mengidentifikasi kekuatan, kelemahan, peluang, dan ancaman suatu wilayah","c":"Membuat peta topografi","d":"Menganalisis iklim","e":"Menentukan batas wilayah"}', 'b', 'SWOT (Strengths, Weaknesses, Opportunities, Threats) digunakan dalam perencanaan wilayah untuk menganalisis potensi dan tantangan.'),
(40, 'Migrasi internasional yang dilakukan akibat kondisi tidak aman (perang, bencana) disebut...', '{"a":"Migrasi ekonomi","b":"Transmigrasi","c":"Urbanisasi","d":"Pengungsian (forced migration/refugee)","e":"Emigrasi sukarela"}', 'd', 'Pengungsi (refugee): orang yang terpaksa meninggalkan negara asalnya akibat perang, kekerasan, atau bencana — bukan atas kehendak sendiri.')
) AS q(nomor, soal, pilihan, jawaban_benar, pembahasan)
WHERE t.title = 'UTBK TKA Soshum - Geografi'
ON CONFLICT (tryout_id, nomor) DO NOTHING;
UPDATE tryouts SET jumlah_soal = 40 WHERE title = 'UTBK TKA Soshum - Geografi';

-- ============================================================
-- SOAL 21-40: TKA SOSHUM - EKONOMI
-- ============================================================
INSERT INTO questions (tryout_id, nomor, soal, pilihan, jawaban_benar, pembahasan, poin)
SELECT t.id, q.nomor, q.soal, q.pilihan::jsonb, q.jawaban_benar, q.pembahasan, 1
FROM tryouts t, (VALUES
(21, 'Pasar oligopoli ditandai dengan...', '{"a":"Satu penjual mendominasi","b":"Banyak penjual produk homogen","c":"Beberapa penjual yang saling bergantung keputusannya","d":"Harga ditentukan pemerintah","e":"Tidak ada hambatan masuk"}', 'c', 'Oligopoli: sedikit perusahaan besar yang saling memengaruhi — keputusan satu perusahaan memengaruhi yang lain. Contoh: industri telekomunikasi.'),
(22, 'Dumping dalam perdagangan internasional adalah...', '{"a":"Larangan ekspor produk tertentu","b":"Menjual produk di luar negeri dengan harga lebih rendah dari harga domestik","c":"Pajak impor tinggi","d":"Pembatasan kuota impor","e":"Subsidi untuk eksportir"}', 'b', 'Dumping: menjual barang di pasar luar negeri dengan harga lebih rendah dari harga di dalam negeri — dianggap praktik perdagangan tidak adil.'),
(23, 'Fungsi konsumsi C = 200 + 0,8Y. Multiplier fiskal adalah...', '{"a":"0,8","b":"1","c":"5","d":"0,2","e":"4"}', 'c', 'Multiplier = 1/(1-MPC) = 1/(1-0,8) = 1/0,2 = 5.'),
(24, 'Bank Dunia (World Bank) berbeda dari IMF karena...', '{"a":"Bank Dunia memberikan pinjaman jangka pendek","b":"Bank Dunia fokus pada pembangunan jangka panjang dan pengentasan kemiskinan","c":"IMF tidak memberikan pinjaman","d":"Bank Dunia mengatur nilai tukar","e":"IMF hanya untuk negara maju"}', 'b', 'Bank Dunia: pinjaman jangka panjang untuk pembangunan ekonomi dan infrastruktur. IMF: stabilisasi keuangan jangka pendek dan neraca pembayaran.'),
(25, 'Harga keseimbangan (equilibrium price) terbentuk ketika...', '{"a":"Penawaran melebihi permintaan","b":"Permintaan melebihi penawaran","c":"Jumlah yang diminta = jumlah yang ditawarkan","d":"Pemerintah menetapkan harga","e":"Produsen memaksimalkan keuntungan"}', 'c', 'Harga keseimbangan: titik perpotongan kurva permintaan dan penawaran → Qd = Qs, tidak ada surplus/kekurangan.'),
(26, 'Depresiasi mata uang domestik berdampak pada ekspor berupa...', '{"a":"Ekspor menjadi lebih mahal bagi pembeli asing","b":"Ekspor menjadi lebih murah bagi pembeli asing → volume ekspor naik","c":"Ekspor tidak terpengaruh","d":"Ekspor meningkat harga, menurun volume","e":"Ekspor terhenti"}', 'b', 'Depresiasi rupiah: 1 USD = lebih banyak rupiah → barang ekspor Indonesia lebih murah dalam USD → pembeli asing lebih banyak membeli.'),
(27, 'Indikator yang membedakan pertumbuhan ekonomi dari pembangunan ekonomi adalah...', '{"a":"Pertumbuhan hanya melihat kenaikan GDP","b":"Pembangunan mencakup kualitas hidup, kesejahteraan, dan pemerataan, bukan hanya GDP","c":"Pertumbuhan lebih penting","d":"Keduanya sama saja","e":"Pembangunan hanya untuk negara miskin"}', 'b', 'Pertumbuhan ekonomi = kenaikan GDP/GNP kuantitatif. Pembangunan ekonomi = proses multidimensi termasuk kualitas hidup, pendidikan, dan pemerataan.'),
(28, 'Mekanisme transmisi kebijakan moneter melalui jalur kredit menyatakan...', '{"a":"Suku bunga langsung mempengaruhi konsumsi","b":"Kebijakan moneter mempengaruhi ketersediaan kredit bank, yang lalu memengaruhi investasi","c":"Bank sentral langsung membeli saham","d":"Moneter tidak berpengaruh pada kredit","e":"Kredit tidak berhubungan dengan investasi"}', 'b', 'Jalur kredit: BI menaikkan suku bunga → kredit bank berkurang → investasi turun → PDB turun → inflasi mereda.'),
(29, 'Teori Purchasing Power Parity (PPP) menyatakan...', '{"a":"Nilai tukar ditentukan oleh kekuatan militer","b":"Nilai tukar jangka panjang mencerminkan perbandingan tingkat harga antar negara","c":"GDP selalu sama antar negara","d":"Ekspor = Impor dalam jangka panjang","e":"Bunga menentukan nilai tukar"}', 'b', 'PPP: dalam jangka panjang, nilai tukar menyesuaikan sehingga harga barang yang sama setara di dua negara.'),
(30, 'Produk Domestik Bruto (PDB) dihitung dengan pendekatan pengeluaran adalah...', '{"a":"PDB = C + I + G + (X-M)","b":"PDB = Upah + Sewa + Bunga + Laba","c":"PDB = Total output - total input","d":"PDB = Ekspor - Impor","e":"PDB = Konsumsi + Tabungan"}', 'a', 'PDB = C (konsumsi) + I (investasi) + G (pengeluaran pemerintah) + (X-M) (ekspor neto).'),
(31, 'Pasar faktor produksi tenaga kerja terdiri dari...', '{"a":"Pasar saham dan obligasi","b":"Penawaran tenaga kerja (individu) dan permintaan tenaga kerja (perusahaan)","c":"Hanya pemerintah yang menentukan upah","d":"Serikat pekerja dan pemerintah","e":"Bursa efek dan pasar uang"}', 'b', 'Pasar tenaga kerja: penawaran dari individu/rumah tangga yang menjual jasa kerja; permintaan dari perusahaan yang membutuhkan tenaga kerja.'),
(32, 'Eksternalitas negatif terjadi ketika...', '{"a":"Manfaat dari suatu kegiatan dinikmati pihak lain tanpa membayar","b":"Biaya dari suatu kegiatan ditanggung pihak ketiga yang tidak terlibat","c":"Produk terlalu mahal bagi konsumen","d":"Perusahaan mendapat keuntungan berlebih","e":"Pemerintah mensubsidi produksi"}', 'b', 'Eksternalitas negatif: biaya sosial > biaya privat. Contoh: polusi pabrik yang merugikan masyarakat sekitar tanpa kompensasi.'),
(33, 'Hiperinflasi terjadi ketika inflasi...', '{"a":"Di bawah 10% per tahun","b":"Antara 10-30% per tahun","c":"Di atas 50% per bulan (sangat ekstrem)","d":"Tepat 100% setahun","e":"Stabil selama bertahun-tahun"}', 'c', 'Hiperinflasi: inflasi sangat ekstrem, biasanya didefinisikan sebagai >50% per bulan (Cagan, 1956). Contoh: Jerman 1923, Zimbabwe 2008.'),
(34, 'Perbedaan utama obligasi dan saham adalah...', '{"a":"Keduanya sama saja","b":"Obligasi adalah instrumen utang (pinjaman berbunga), saham adalah kepemilikan","c":"Saham lebih aman dari obligasi","d":"Obligasi hanya untuk pemerintah","e":"Saham memberikan bunga tetap"}', 'b', 'Obligasi (bond): surat utang dengan bunga tetap. Saham (stock): bukti kepemilikan perusahaan, dividen tidak pasti.'),
(35, 'Kebijakan fiskal ekspansif dilakukan dengan cara...', '{"a":"Menaikkan suku bunga","b":"Meningkatkan pengeluaran pemerintah dan/atau menurunkan pajak","c":"Mengurangi jumlah uang beredar","d":"Menaikkan pajak","e":"Menurunkan pengeluaran pemerintah"}', 'b', 'Fiskal ekspansif: menstimulasi perekonomian dengan menambah belanja pemerintah atau memotong pajak → meningkatkan AD.'),
(36, 'Konsep marginal propensity to consume (MPC) = 0,75 artinya...', '{"a":"75% pendapatan ditabung","b":"Dari setiap tambahan pendapatan Rp 1, sebesar Rp 0,75 dikonsumsi","c":"Harga naik 75% jika konsumsi naik","d":"75% produk dikonsumsi domestik","e":"Ekspor 75% dari produksi"}', 'b', 'MPC = ΔC/ΔY = 0,75: dari setiap penambahan pendapatan Rp 1, konsumsi bertambah Rp 0,75 dan tabungan Rp 0,25.'),
(37, 'Pengangguran struktural terjadi akibat...', '{"a":"Resesi ekonomi sementara","b":"Pekerja berpindah kerja","c":"Ketidakcocokan keterampilan pekerja dengan permintaan industri akibat perubahan teknologi","d":"Musim produksi rendah","e":"Kenaikan upah minimum"}', 'c', 'Pengangguran struktural: akibat perubahan struktural ekonomi (otomatisasi, digitalisasi) → keterampilan lama tidak relevan.'),
(38, 'Inflasi yang terjadi akibat kenaikan biaya produksi (upah, bahan baku) disebut...', '{"a":"Demand-pull inflation","b":"Cost-push inflation","c":"Built-in inflation","d":"Hyperinflation","e":"Deflasi"}', 'b', 'Cost-push inflation: biaya produksi naik (upah, energi) → produsen naikkan harga → inflasi. Berbeda dengan demand-pull (permintaan berlebih).'),
(39, 'Lembaga penjamin simpanan (LPS) di Indonesia berfungsi untuk...', '{"a":"Memberikan kredit murah","b":"Menjamin simpanan nasabah bank hingga batas tertentu jika bank gagal","c":"Mengatur suku bunga","d":"Menerbitkan obligasi pemerintah","e":"Mengawasi pasar saham"}', 'b', 'LPS menjamin simpanan nasabah (max Rp 2 miliar/nasabah/bank) — melindungi deposan jika bank mengalami likuidasi.'),
(40, 'Konsep "invisible hand" Adam Smith dalam ekonomi pasar menyatakan...', '{"a":"Pemerintah harus mengatur semua harga","b":"Mekanisme pasar (harga) secara alami mengalokasikan sumber daya secara efisien tanpa campur tangan pemerintah","c":"Monopoli menguntungkan masyarakat","d":"Perdagangan internasional merugikan","e":"Distribusi pendapatan selalu merata"}', 'b', '"Tangan tak terlihat" Adam Smith: dalam pasar bebas, individu yang mengejar kepentingan pribadi secara tidak sengaja mendorong kebaikan masyarakat melalui mekanisme harga.')
) AS q(nomor, soal, pilihan, jawaban_benar, pembahasan)
WHERE t.title = 'UTBK TKA Soshum - Ekonomi'
ON CONFLICT (tryout_id, nomor) DO NOTHING;
UPDATE tryouts SET jumlah_soal = 40 WHERE title = 'UTBK TKA Soshum - Ekonomi';

-- ============================================================
-- SOAL 21-40: TKA SOSHUM - SOSIOLOGI
-- ============================================================
INSERT INTO questions (tryout_id, nomor, soal, pilihan, jawaban_benar, pembahasan, poin)
SELECT t.id, q.nomor, q.soal, q.pilihan::jsonb, q.jawaban_benar, q.pembahasan, 1
FROM tryouts t, (VALUES
(21, 'Auguste Comte dianggap sebagai bapak sosiologi karena...', '{"a":"Menulis Das Kapital","b":"Menciptakan istilah "sociologie" dan mengembangkan positivisme","c":"Menemukan teori evolusi sosial","d":"Mendirikan universitas pertama","e":"Menulis The Protestant Ethic"}', 'b', 'Auguste Comte (Prancis, 1798-1857) menciptakan istilah "sociologie" dan mengembangkan pendekatan positivis untuk mempelajari masyarakat.'),
(22, 'Status sosial ascribed (ditetapkan) berbeda dari achieved (dicapai) karena...', '{"a":"Ascribed diperoleh melalui usaha","b":"Ascribed diberikan sejak lahir tanpa pilihan (ras, jenis kelamin, keturunan)","c":"Achieved tidak dapat berubah","d":"Ascribed hanya di masyarakat modern","e":"Keduanya sama saja"}', 'b', 'Ascribed status: diperoleh tanpa usaha (warisan, jenis kelamin, kasta). Achieved status: diperoleh melalui usaha dan prestasi.'),
(23, 'Norma sosial yang paling kuat sanksinya adalah...', '{"a":"Folkways (kebiasaan)","b":"Mores (tata kelakuan)","c":"Custom (adat)","d":"Hukum formal","e":"Etiket"}', 'd', 'Hierarki norma dari lemah ke kuat: etiket → folkways → mores → custom → hukum formal (sanksi paling tegas dari negara).'),
(24, 'Teori struktural fungsional Parsons menggunakan konsep AGIL yang meliputi...', '{"a":"Authority, Growth, Innovation, Leadership","b":"Adaptation, Goal attainment, Integration, Latency","c":"Agency, Government, Ideology, Labor","d":"Action, Goals, Interests, Laws","e":"Alienation, Groups, Identity, Legitimacy"}', 'b', 'AGIL Parsons: Adaptation (adaptasi), Goal attainment (pencapaian tujuan), Integration (integrasi), Latency/Pattern maintenance (pemeliharaan pola).'),
(25, 'Kriminalitas menurut perspektif sosiologi merupakan...', '{"a":"Gangguan mental semata","b":"Akibat gen buruk","c":"Konstruksi sosial — ditentukan oleh definisi dan norma masyarakat","d":"Selalu merugikan individu","e":"Tidak dapat dipelajari"}', 'c', 'Kriminalitas adalah konstruksi sosial: apa yang dianggap kejahatan bergantung pada waktu, tempat, dan norma masyarakat yang mendefinisikannya.'),
(26, 'Proses difusi budaya paling cepat terjadi melalui...', '{"a":"Isolasi geografis","b":"Media massa dan teknologi informasi","c":"Tradisi lisan antar generasi","d":"Perpustakaan","e":"Sistem pendidikan formal"}', 'b', 'Media massa (TV, internet, media sosial) mempercepat difusi budaya secara masif dan global.'),
(27, 'Dalam penelitian sosiologi, teknik snowball sampling digunakan ketika...', '{"a":"Populasinya besar dan mudah diidentifikasi","b":"Populasinya tersembunyi atau sulit dijangkau — responden merujuk responden lain","c":"Peneliti ingin sampel representatif","d":"Populasinya homogen","e":"Waktu penelitian sangat singkat"}', 'b', 'Snowball: cocok untuk populasi tersembunyi (pengguna narkoba, kelompok marginal) — satu responden merujuk yang lain.'),
(28, 'Fenomena "gated community" (perumahan berpagar) mencerminkan...', '{"a":"Kemajuan teknologi","b":"Segregasi sosial spasial antara kelas atas dan masyarakat umum","c":"Kerjasama komunitas","d":"Pemerataan pembangunan","e":"Integrasi sosial yang baik"}', 'b', 'Gated community: kelompok kelas atas memisahkan diri secara fisik → segregasi sosial dan pengurangan interaksi antar kelas.'),
(29, 'Konsep anomie menurut Durkheim terjadi ketika...', '{"a":"Norma sosial terlalu ketat","b":"Norma sosial melemah atau tidak jelas, menyebabkan individu kehilangan panduan perilaku","c":"Masyarakat terlalu homogen","d":"Integrasi sosial terlalu kuat","e":"Teknologi berkembang cepat"}', 'b', 'Anomie (Durkheim): kondisi "tanpa norma" — saat perubahan sosial cepat melemahkan aturan lama sebelum norma baru terbentuk.'),
(30, 'Pemberdayaan masyarakat (community empowerment) bertujuan...', '{"a":"Membuat masyarakat bergantung pada bantuan luar","b":"Meningkatkan kemampuan masyarakat untuk mengidentifikasi dan memecahkan masalah sendiri","c":"Menghilangkan perbedaan budaya","d":"Mempercepat urbanisasi","e":"Mengintegrasikan masyarakat ke sistem global"}', 'b', 'Pemberdayaan: proses meningkatkan kapasitas dan kemandirian masyarakat untuk mengambil kontrol atas kehidupan mereka sendiri.'),
(31, 'Interaksi sosial yang bersifat disosiatif meliputi...', '{"a":"Kerjasama dan akomodasi","b":"Asimilasi dan akulturasi","c":"Persaingan, kontravensi, dan konflik","d":"Asimilasi dan kerjasama","e":"Integrasi dan akomodasi"}', 'c', 'Interaksi disosiatif (mengarah pada perpecahan): persaingan (competition), kontravensi (contravention), dan konflik.'),
(32, 'Teori labeling (penandaan) dalam sosiologi penyimpangan menyatakan bahwa...', '{"a":"Penyimpangan bawaan sejak lahir","b":"Seseorang menjadi devian karena diberi label devian oleh masyarakat dan menginternalisasinya","c":"Penyimpangan hanya pada kelas bawah","d":"Hukuman selalu efektif mencegah penyimpangan","e":"Media tidak berpengaruh pada penyimpangan"}', 'b', 'Teori labeling (Becker): individu yang dilabeli "devian" cenderung menginternalisasi label tersebut dan berperilaku sesuai label.'),
(33, 'Modernisasi dalam perspektif sosiologi berarti...', '{"a":"Westernisasi penuh","b":"Proses transformasi dari masyarakat tradisional menuju masyarakat modern dengan rasionalitas dan teknologi","c":"Pembangunan infrastruktur fisik","d":"Adopsi semua budaya asing","e":"Penghapusan tradisi"}', 'b', 'Modernisasi: transformasi struktural-kultural menuju masyarakat yang lebih rasional, birokratis, dan berbasis ilmu pengetahuan.'),
(34, 'Kekerasan dalam rumah tangga (KDRT) merupakan masalah sosial karena...', '{"a":"Hanya berdampak pada individu","b":"Merugikan banyak pihak dan melanggar norma serta hak asasi manusia","c":"Merupakan urusan privat yang tidak perlu diintervensi","d":"Tidak ada regulasi yang mengatur","e":"Hanya terjadi di kalangan tertentu"}', 'b', 'KDRT adalah masalah sosial: berdampak luas (korban, anak, komunitas), melanggar HAM, dan memerlukan intervensi hukum dan sosial.'),
(35, 'Dalam sosiologi, "peran sosial" berbeda dari "status sosial" karena...', '{"a":"Keduanya sama","b":"Status adalah posisi (kedudukan), peran adalah perilaku yang diharapkan dari status tersebut","c":"Peran tidak dapat berubah","d":"Status hanya ada di masyarakat modern","e":"Peran adalah posisi, status adalah perilaku"}', 'b', 'Status = posisi seseorang dalam struktur sosial. Peran = perilaku yang diharapkan dari orang yang menduduki status tersebut.'),
(36, 'Penelitian sosial yang menggunakan angket/kuesioner untuk mengumpulkan data dari banyak responden disebut...', '{"a":"Penelitian etnografi","b":"Penelitian survei","c":"Penelitian eksperimen","d":"Studi kasus","e":"Fenomenologi"}', 'b', 'Penelitian survei: mengumpulkan data secara sistematis dari sampel besar menggunakan instrumen terstandar (kuesioner).'),
(37, 'Konsep "modal sosial" (social capital) menurut Putnam meliputi...', '{"a":"Kekayaan materi komunitas","b":"Jaringan sosial, norma, dan kepercayaan yang memfasilitasi kerjasama","c":"Modal ekonomi yang dimiliki bersama","d":"Infrastruktur fisik komunitas","e":"Tingkat pendidikan rata-rata"}', 'b', 'Modal sosial Putnam: jaringan, norma kepercayaan, dan kerjasama yang meningkatkan efisiensi masyarakat dan membangun solidaritas.'),
(38, 'Etnosentrisme adalah...', '{"a":"Kecenderungan menganggap budaya sendiri sebagai yang paling baik dan menggunakannya untuk menilai budaya lain","b":"Menghargai semua budaya secara setara","c":"Studi tentang etnis tertentu","d":"Percampuran budaya","e":"Penolakan budaya sendiri"}', 'a', 'Etnosentrisme: menilai budaya lain berdasarkan standar budaya sendiri, menganggap budaya sendiri lebih superior.'),
(39, 'Gerakan sosial (social movement) berbeda dari kerumunan (crowd) karena...', '{"a":"Gerakan sosial lebih banyak orangnya","b":"Gerakan sosial memiliki tujuan, organisasi, dan berlangsung dalam waktu yang lebih panjang","c":"Kerumunan lebih terorganisir","d":"Gerakan sosial selalu melibatkan kekerasan","e":"Keduanya sama saja"}', 'b', 'Gerakan sosial: kolektif, terorganisir, bertujuan mengubah atau mempertahankan aspek masyarakat, berlangsung dalam jangka waktu tertentu.'),
(40, 'Konsekuensi sosial dari revolusi industri 4.0 terhadap ketenagakerjaan adalah...', '{"a":"Semua pekerjaan hilang","b":"Otomatisasi menggantikan pekerjaan rutin → pekerja perlu reskilling, lahir lapangan kerja baru berbasis digital","c":"Pengangguran tidak terpengaruh","d":"Upah pekerja naik otomatis","e":"Kesenjangan ekonomi berkurang"}', 'b', 'Industri 4.0: robot dan AI menggantikan pekerjaan rutin → risiko pengangguran struktural → kebutuhan reskilling dan adaptasi kompetensi.')
) AS q(nomor, soal, pilihan, jawaban_benar, pembahasan)
WHERE t.title = 'UTBK TKA Soshum - Sosiologi'
ON CONFLICT (tryout_id, nomor) DO NOTHING;
UPDATE tryouts SET jumlah_soal = 40 WHERE title = 'UTBK TKA Soshum - Sosiologi';

-- Konfirmasi akhir
SELECT t.title, COUNT(q.id) as jumlah_soal
FROM tryouts t
LEFT JOIN questions q ON q.tryout_id = t.id
WHERE t.title LIKE 'UTBK%'
GROUP BY t.title
ORDER BY t.title;
